// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaywxijzwtswizhhnrfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdheXd4aWp6d3Rzd2l6aGhucmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODQ4MTUsImV4cCI6MjA2OTU2MDgxNX0.xt2XklMoVFbOWpv1FhTlZX41SIsFLlQ1wWbn-B59PmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});